---
- name: APT update and upgrade
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3
    - python3-pip
    - python3-venv
